apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress_eks
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/flamingo1332/wordpress_eks_argo'
    path: /apps
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
