apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring  # Assuming you have a 'monitoring' namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://grafana.github.io/helm-charts'  # Grafana Helm chart repository
    chart: grafana
    targetRevision: '6.1.17'  # Use the latest stable version compatible with your cluster
    helm:
      values: |-
        adminUser: admin
        adminPassword: password
        service:
          type: ClusterIP  # Change to LoadBalancer if you want external access
        ingress:
          enabled: false  # Set to true and configure if you need ingress
        persistence:
          enabled: true  # Enable if you want to persist Grafana data
          size: 10Gi
        # Additional Grafana configuration
