apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"  # Adjust the sync wave as needed
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring  # Assuming you have a 'monitoring' namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'  # Prometheus Helm chart repository
    chart: kube-prometheus-stack
    targetRevision: '25.8.2'  # Use the latest stable version compatible with your cluster
    helm:
      values: |-
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 2d  
        alertmanager:
          enabled: false  
        grafana:
          enabled: true  
          adminPassword: password
          
