apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  # labels:
  #   environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' # URL of the Helm chart repository
    chart: wordpress
    targetRevision: '19.0.4' 
    helm:
      values: |-
        wordpressUsername: user
        wordpressPassword: password
        wordpressEmail: user@example.com
        wordpressBlogName: My Blog

        externalDatabase:
          host: localhost  # Replace with your MySQL host IP
          port: 3306             # Default MySQL port, change if different
          user: user
          password: password
          database: wordpress

        mariadb:
          enabled: false

        persistence:
          enabled: true
          size: 4Gi

        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 1024Mi
            cpu: 500m
        service:
          type: NodePort
        # ingress:
        #   enabled: false
        #   hostname: wordpress.example.com

        
        