apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress_hpa
  namespace: wordpress  # Change this to the namespace of your deployment
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress  # Replace with the name of your deployment
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization percentage
