apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' # URL of the Helm chart repository
    chart: wordpress
    targetRevision: 'latest' 
    helm:
      valueFiles:
        - values.yaml
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

